import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container" style={{ fontFamily: 'var(--font-geist-sans)' }}>
        <div class="Nav">
          <h1>Products</h1>
          <div class="Link">
            <Link href="/">All Products</Link>
            <Link href="/beauty">Beauty</Link>
            <Link href="/fragrances">Fragrances</Link>
            <Link href="/furniture">Furniture</Link>
            <Link href="/groceries">Groceries</Link>
          </div>  
          <button className="alisverissepeti">🛒</button>
        </div>
        {children}
      </body>
    </html>
  );
}
